"""add bank_packets

Revision ID: 0661b079e774
Revises: 2852903783fe
Create Date: 2026-08-21 14:53:11.302770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0661b079e774'
down_revision: Union[str, None] = '2852903783fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_packets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('netting_run_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gross_obligations_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_matched_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_settlement_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fx_friction_savings_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('matches_count', sa.Integer(), nullable=False),
    sa.Column('auto_eligible_count', sa.Integer(), nullable=False),
    sa.Column('needs_review_count', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['netting_run_id'], ['netting_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netting_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_packets')
    # ### end Alembic commands ###
