"""add explanation fields to offset_matches

Revision ID: 2852903783fe
Revises: 7d55649623f1
Create Date: 2026-08-21 14:45:57.366676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2852903783fe'
down_revision: Union[str, None] = '7d55649623f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offset_matches', sa.Column('confidence_tier', sa.String(length=1), nullable=True))
    op.add_column('offset_matches', sa.Column('eligibility_flag', sa.String(length=20), nullable=True))
    op.add_column('offset_matches', sa.Column('justification_text', sa.Text(), nullable=True))
    op.add_column('offset_matches', sa.Column('ai_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offset_matches', 'ai_generated')
    op.drop_column('offset_matches', 'justification_text')
    op.drop_column('offset_matches', 'eligibility_flag')
    op.drop_column('offset_matches', 'confidence_tier')
    # ### end Alembic commands ###
