"""add netting_runs, offset_matches

Revision ID: 7d55649623f1
Revises: 09c0e9bc7d3d
Create Date: 2026-08-21 14:20:02.396296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d55649623f1'
down_revision: Union[str, None] = '09c0e9bc7d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netting_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('obligations_considered', sa.Integer(), nullable=False),
    sa.Column('matches_created', sa.Integer(), nullable=False),
    sa.Column('fx_snapshot', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offset_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('netting_run_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('payable_obligation_id', sa.UUID(), nullable=False),
    sa.Column('receivable_obligation_id', sa.UUID(), nullable=False),
    sa.Column('settlement_bucket_start', sa.Date(), nullable=False),
    sa.Column('settlement_bucket_end', sa.Date(), nullable=False),
    sa.Column('matched_amount_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['netting_run_id'], ['netting_runs.id'], ),
    sa.ForeignKeyConstraint(['payable_obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['receivable_obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offset_matches')
    op.drop_table('netting_runs')
    # ### end Alembic commands ###
