"""initial schema: smes, counterparties, obligations, payment_events

Revision ID: 8bba095d9965
Revises: 
Create Date: 2026-08-21 14:03:47.065007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bba095d9965'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('RECEIVABLE', 'PAYABLE', name='obligationdirection'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expected_settlement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SETTLED', 'NETTED', name='obligationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_events')
    op.drop_table('obligations')
    op.drop_table('smes')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
