"""add payment_behavior_profiles

Revision ID: cd7a21d4994a
Revises: 8bba095d9965
Create Date: 2026-08-21 14:07:28.655180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7a21d4994a'
down_revision: Union[str, None] = '8bba095d9965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_behavior_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('on_time_ratio', sa.Float(), nullable=False),
    sa.Column('median_delay_days', sa.Float(), nullable=False),
    sa.Column('delay_variance', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('most_recent_payment_date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counterparty_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_behavior_profiles')
    # ### end Alembic commands ###
