"""phase2: invoices, financing, settlement, compliance, audit, currency exposure, bank partners

Revision ID: febd8c4463e2
Revises: 0661b079e774
Create Date: 2026-08-21 20:04:39.108603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'febd8c4463e2'
down_revision: Union[str, None] = '0661b079e774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'USER', name='auditactor'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_nbfc_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner_type', sa.Enum('NBFC', 'BANK', name='partnertype'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('min_auto_tier', sa.String(length=1), nullable=False),
    sa.Column('typical_latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_exposures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_receivable_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('gross_payable_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('net_exposure_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    # obligationdirection enum already exists (created with the obligations table); reference it
    sa.Column('direction', postgresql.ENUM('RECEIVABLE', 'PAYABLE', name='obligationdirection', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('po_reference', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('SEEDED', 'EXTRACTED', name='invoicesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('underwriting_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=False),
    sa.Column('reliability_score_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('advance_pct', sa.Float(), nullable=False),
    sa.Column('fee_pct', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Enum('APPROVE', 'REVIEW', 'REJECT', name='underwritingoutcome'), nullable=False),
    sa.Column('limited_data', sa.Boolean(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['reliability_score_id'], ['reliability_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financing_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('underwriting_decision_id', sa.UUID(), nullable=True),
    sa.Column('bank_nbfc_partner_id', sa.UUID(), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('advance_pct', sa.Float(), nullable=False),
    sa.Column('fee_pct', sa.Float(), nullable=False),
    sa.Column('advance_amount_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('fee_amount_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('net_proceeds_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENTED', 'ACCEPTED', 'EXPIRED', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_nbfc_partner_id'], ['bank_nbfc_partners.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['underwriting_decision_id'], ['underwriting_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financing_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('financing_offer_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('bank_nbfc_partner_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('OPPORTUNITY', 'OFFER', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'DISBURSED', 'SETTLED', name='financingstage'), nullable=False),
    sa.Column('lender_decision', sa.Enum('APPROVE', 'REVIEW', 'REJECT', name='lenderdecision'), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_nbfc_partner_id'], ['bank_nbfc_partners.id'], ),
    sa.ForeignKeyConstraint(['financing_offer_id'], ['financing_offers.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('financing_offer_id', sa.UUID(), nullable=True),
    sa.Column('cash_before_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('cash_after_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('runway_delta_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financing_offer_id'], ['financing_offers.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['sme_id'], ['smes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('financing_agreement_id', sa.UUID(), nullable=True),
    sa.Column('requirement_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'PENDING', 'ILLUSTRATIVE', name='compliancestatus'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financing_agreement_id'], ['financing_agreements.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_type', sa.Enum('NET', 'DIRECT', 'FINANCING', name='settlementtype'), nullable=False),
    sa.Column('offset_match_id', sa.UUID(), nullable=True),
    sa.Column('financing_agreement_id', sa.UUID(), nullable=True),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financing_agreement_id'], ['financing_agreements.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['offset_match_id'], ['offset_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('obligations', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'obligations', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.drop_column('obligations', 'invoice_id')
    op.drop_table('settlements')
    op.drop_table('compliance_requirements')
    op.drop_table('liquidity_events')
    op.drop_table('financing_agreements')
    op.drop_table('financing_offers')
    op.drop_table('underwriting_decisions')
    op.drop_table('invoices')
    op.drop_table('currency_exposures')
    op.drop_table('bank_nbfc_partners')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
